export enum AppEvents {
  TOGGLE_DATE = 'TOGGLE_DATE',
  CREATE_HABIT = 'CREATE_HABIT',
  REMOVE_HABIT = 'REMOVE_HABITÍ',
  LOAD_DATES = 'LOAD_DATES',
  SET_USER_INFO = 'SET_USER_INFO',
  RESET_USER_INFO = 'RESET_USER_INFO',
}
